apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -production

commonLabels:
  environment: production

namespace: nginx-prod

images:
- name: nginx
  newTag: 1.19.2
